name: Yggdrasil Notícias

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Executar robo
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python bot_autorespost.py
