name: Automação Yggdrasil 24h

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Executar Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot_autorespost.py
